### ISSUE TITLE
this extension will cause VS2015 not responding

### ISSUE THREAD

**Issue by zqooqz0986** [tom-englert/ResXResourceManager#103]

**Comment by sjoerdboerhout** [comment]
I can confirm this issue. Since the last update (12 march) every clean or update action on a random project causes a freeze of VS2015 for at least 3 minutes before the action is started. After disabling ResX Manager the problem was solved.

**Comment by FrancescoGiossi** [comment]
Same here.
VS2015 randomly freezes when building or cleaning a solution. Disabling ResxResourceManager extension fix the problem.
The build of one very huge solution I work with since at least 8 years ALWAYS freezes Visual Studio (I use this extension since the beginning, never had a single problema with it).
This kind of problem has never happened before.

**Comment by tom-englert** [comment]
Duplicate of #97
