### ISSUE TITLE
Option for automatic removing of empty entries

### ISSUE THREAD

**Issue by DJmRek** [tom-englert/ResXResourceManager#166]
Hi there, we ran into a problem after enabling the localizable feature on our froms. It's caused by the automatic removal of empty resx-entries by ResxResourceManager. Is it possible to add an configuration option for that behavior?

**Comment by tom-englert** [comment]
Sure, if someone likes to contribute this feature.

**Comment by DJmRek** [comment]
Hi Tom, could you give me a hint were to start? E.g. where the ResXResourceManager reacts to outside changes of the resx files?

**Comment by tom-englert** [comment]
Here is where empty items are removed:
https://github.com/tom-englert/ResXResourceManager/blob/a5d62dca05f0e861e415bfffef2b8151843b73b4/ResXManager.Model/ResourceLanguage.cs#L430
(I did this because many users requested it that way)
And here is the configuration:
https://github.com/tom-englert/ResXResourceManager/blob/a5d62dca05f0e861e415bfffef2b8151843b73b4/ResXManager.Model/Configuration.cs#L22

**Comment by tom-englert** [comment]
@yinyue200 can you add the translations for the two new strings?
