### ISSUE TITLE
Not save last time selected in  "Move to Resource  " 

### ISSUE THREAD

**Issue by maikebing** [tom-englert/ResXResourceManager#2]
this is good work! 
I like it very much

![image](https://cloud.githubusercontent.com/assets/3445167/22401832/47966926-e61e-11e6-926b-a15b88bd77ee.png)
Every time you need to choose, so it is not convenient.

**Comment by tom-englert** [comment]
Which item do you mean? Or do you want to omit the whole dialog?

**Comment by maikebing** [comment]
1st. 
Resource:

**Comment by tom-englert** [comment]
It remembers the last selection, but if you have a resource file in the current assembly, it defaults to the resources of the assembly.
This is because if it only remembers the last selection, I frequently ended up with resources added to the wrong assembly. 
It currently assumes that you have either one single resource assembly per solution, or one resource per assembly. In the latter case you rather want to add resources to the local assemblies resources than to the resources of another assembly - so I implemented it this way.

Any idea how this could be improved without breaking the current workflow?

**Comment by tom-englert** [comment]
@maikebing any proposals on this?

**Comment by maikebing** [comment]
We recently had a Chinese New Year holiday, and my child will soon be born, so I'm sorry to reply to you so late!
We can use a common resource file for each assembly by default! Those who do not have the resources of the document can be used by default, such as class!
Forms, controls, components and other resources of the document is directly added to the string in their own resources document.

**Comment by maikebing** [comment]
如果有选项更好， 我可以选择 是按照上面的方式， 或者是所有字符串资源都放在一个资源文件中。 

If there are options better, I can choose is in accordance with the above way, or all the string resources are placed in a resource file.

**Comment by tom-englert** [comment]
I have made some improvements, that should increase usability:
- if the assembly containing the source file has a resource, this is the first entry
- the resource that you used during the last operation will be the second entry
- then all other entries follow as before

This way it's fast changing from the recommended to the last used entry...

**Comment by tom-englert** [comment]
@maikebing did you try it?

**Comment by tom-englert** [comment]
I assume this is fitting your needs...
